// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your_API_Key_Here',
    appId: 'Your_App_ID_Here',
    messagingSenderId: 'Your_Messaging_Sender_ID_Here',
    projectId: 'Your_Project_ID_Here',
    authDomain: 'Your_Auth_Domain_Here',
    storageBucket: 'Your_Storage_Bucket_Here',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Your_API_Key_Here',
    appId: 'Your_App_ID_Here',
    messagingSenderId: 'Your_Messaging_Sender_ID_Here',
    projectId: 'Your_Project_ID_Here',
    storageBucket: 'Your_Storage_Bucket_Here',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'You_API_Key_Here',
    appId: 'Your_App_ID_Here',
    messagingSenderId: 'Your_Messaging_Sender_ID_Here',
    projectId: 'Your_Project_ID_Here',
    storageBucket: 'Your_Storage_Bucket_Here',
    iosBundleId: 'com.example.agriwealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Your_API_Key_Here',
    appId: '1:868170071909:ios:33452349b989ca26322b8c',
    messagingSenderId: 'Your_Messaging_Sender_ID_Here',
    projectId: 'Your_Project_ID_Here',
    storageBucket: 'Your_Storage_Bucket_Here',
    iosBundleId: 'com.example.agriwealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'Your_API_Key_Here',
    appId: 'Your_App_ID_Here',
    messagingSenderId: 'Your_Messaging_Sender_ID_Here',
    projectId: 'Your_Project_ID_Here',
    authDomain: 'Your_Auth_Domain_Here',
    storageBucket: 'Your_Storage_Bucket_Here',
  );
}
